import { css } from '@emotion/react';
import Head from 'next/head';
import Link from 'next/link';
import React from 'react';

const navBar = css`
  margin-right: 2px;
`;

export default function homepage() {
  return (
    <div>
      <Head>
        <title>Gym Shop</title>
        <meta className="description" content="Generated by me" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to your favorite Gym Shop</h1>
      <nav
        id="soomagicmenu-main"
        className="soomagicmenu hide-below-1024"
        css={navBar}
      >
        <ul>
          <li>
            <Link href="bodybuilding">Bodybuilding</Link>
          </li>
          <li>
            <Link href="powerlifting">Powelifting</Link>
          </li>
          <li>
            <Link href="strongman">Strongman</Link>
          </li>
        </ul>
      </nav>
    </div>
  );
}
