import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import products from '../products.json';
import barbell from '../public/barbell.jpeg';
import bench from '../public/bench.jpeg';
import dumbell from '../public/dumbel.avif';
import rack from '../public/rack.jpeg';
import styles from '../styles/Home.module.css';

export default function Home({ id, name, price, img }) {
  console.log(id, name, price, img);
  return (
    <div className={styles.container}>
      <Head>
        <title>Gym Shop</title>
        <meta className="Description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Heavy Heaven</h1>
      <div>
        <div>
          <ul>
            <li>
              <Link href="/singepages/bodybuilding">
                <a>Bodybuilding</a>
              </Link>
            </li>
            <li>
              <Link href="./singepages/powerlifting">
                <a>Powelifting</a>
              </Link>
            </li>
            <li>
              <Link href="./singepages/strongman">
                <a>Strongman</a>
              </Link>
            </li>
          </ul>
        </div>
        <ul>
          <li>
            <Image src={barbell} alt="barbell" width={300} height={300} />
            Barbell
          </li>
          <li>
            <Image src={bench} alt="bench" width={300} height={300} />
            Bench
          </li>
          <li>
            <Image src={dumbell} alt="dumbell" width={300} height={300} />
            Dumbell
          </li>
          <li>
            <Image src={rack} alt="rack" width={300} height={300} />
            Rack
          </li>
        </ul>
      </div>

      {id}
      {products.map((product) => {
        return (
          <div key={id} className=" font-sans">
            <container className="w-full">
              <img src={img} alt="Pic" className="Images" loading="lazy" />
            </container>
            <form className="flex-auto p-6">
              <div className="flex flex-wrap">
                <h1 className="flex-auto text-lg font-semibold text-slate-900">
                  {name}
                </h1>
                <div className="text-lg font-semibold text-slate-500">
                  {price}
                </div>
                <div className="w-full flex-none text-sm font-medium text-slate-700 mt-2">
                  In stock
                </div>
              </div>
              <div className="flex items-baseline mt-4 mb-6 pb-6 border-b border-slate-200">
                <div className="space-x-2 flex text-sm labelContainer">
                  <label>
                    <input className="sr-only peer" name="size" type="radio" />
                    <div className="w-9 h-9 rounded-lg flex items-center justify-center text-slate-700 peer-checked:font-semibold peer-checked:bg-slate-900 peer-checked:text-white ">
                      5kg
                    </div>
                  </label>
                  <label>
                    <input className="sr-only peer" name="size" type="radio" />
                    <div className="w-9 h-9 rounded-lg flex items-center justify-center text-slate-700 peer-checked:font-semibold peer-checked:bg-slate-900 peer-checked:text-white">
                      10kg
                    </div>
                  </label>
                  <label>
                    <input className="sr-only peer" name="size" type="radio" />
                    <div className="w-9 h-9 rounded-lg flex items-center justify-center text-slate-700 peer-checked:font-semibold peer-checked:bg-slate-900 peer-checked:text-white">
                      10kg
                    </div>
                  </label>
                  <label>
                    <input className="sr-only peer" name="size" type="radio" />
                    <div className="w-9 h-9 rounded-lg flex items-center justify-center text-slate-700 peer-checked:font-semibold peer-checked:bg-slate-900 peer-checked:text-white">
                      15kg
                    </div>
                  </label>
                  <label>
                    <input className="sr-only peer" name="size" type="radio" />
                    <div className="w-9 h-9 rounded-lg flex items-center justify-center text-slate-700 peer-checked:font-semibold peer-checked:bg-slate-900 peer-checked:text-white">
                      50kg
                    </div>
                  </label>
                </div>
              </div>
              <div className="flex space-x-4 mb-6 text-sm font-medium">
                <div className="flex-auto flex space-x-4">
                  <button className="h-10 px-6 font-semibold rounded-md bg-black text-white">
                    <Link href={'/product/' + product.id}>
                      <a>Add to muscle</a>
                    </Link>
                  </button>
                </div>
                <button
                  className="flex-none flex items-center justify-center w-9 h-9 rounded-md text-slate-300 border border-slate-200"
                  type="button"
                  aria-label="Like"
                >
                  <svg
                    width="10"
                    height="10"
                    fill="currentColor"
                    aria-hidden="true"
                  >
                    <path
                      fillRule="evenodd"
                      clipRule="evenodd"
                      d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z"
                    />
                  </svg>
                </button>
              </div>
              <p className="text-sm text-slate-700">
                Free shipping on weights below 20kg
              </p>
            </form>
          </div>
        );
      })}
    </div>
  );
}
