import { css } from '@emotion/react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Heropage from '../Components/Heropage';
import Layout from '../Components/Layout';
import barbell from '../public/barbell.jpeg';
import bench from '../public/bench.jpeg';
import dumbell from '../public/dumbel.avif';
import rack from '../public/rack.jpeg';
import styles from '../styles/Home.module.css';

const featured = css`
  display: flex;
  gap: 10rem;
  font-size: 30px;
  text-align: center;
  justify-content: center;
  list-style: none;
  padding-top: 40px;
`;

export default function Home({ id, name, price, img }) {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Gym Shop</title>
          <meta
            className="Description"
            content="Generated by create next app"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Heropage />
        <h1 style={{ textAlign: 'center' }}>Featured Products</h1>
        <div>
          <ul css={featured}>
            <Link href={'/product/' + img}>
              <li>
                <Image src={barbell} alt="barbell" width={300} height={300} />
                Barbells
              </li>
            </Link>
            <Link href={'/product/' + img}>
              <li>
                <Image src={bench} alt="bench" width={300} height={300} />
                Benches
              </li>
            </Link>
            <Link href={'/product/' + img}>
              <li>
                <Image src={dumbell} alt="dumbell" width={300} height={300} />
                Dumbells
              </li>
            </Link>
            <Link href={'/product/' + img}>
              <li>
                <Image src={rack} alt="rack" width={300} height={300} />
                Racks
              </li>
            </Link>
          </ul>
        </div>
      </div>
    </Layout>
  );
}
